### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by henask12** [henask12/JavaScript-Capstone#21]
Dear Reviewer

- we are two student in this group and the below is the link to our project 
https://github.com/henask12/JavaScript-Capstone

Regards

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Kindly make sure to distribute the tasks equally between all team members. Currently, for @henask12 and @bohaz, the points for each team member stand at 15 and 22 respectively which is too big of a margin between the distributed tasks. Kindly make sure that the difference in points is less than 5 at most.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @henask12 and @bohaz,

# APPROVED 🟢 

✔️ Similar task points

_Outstanding implementation of the features in this milestone  and changes suggested by the previous reviewer.✔️ _

Kudos to you 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

## CONGRATULATIONS! 🎉 

# OPTIONAL SUGGESTIONS ♻️ 

Kindly check the comment below 👇 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
